name: "Incremental coverage check"
description: "Incremental coverage check"
author: "Velis"
inputs:
  clover_coverage_json:
    description: "Clover coverage json"
    default: "none"
  py_coverage_json:
    description: "Python coverage json"
    default: "none"
  logging_level:
    description: "Loging level"
    default: "INFO"
  base_ref:
    description: Base branch
    defaut: $GITHUB_BASE_REF
  head_ref:
    description: Base branch
    defaut: "HEAD"
  repository:
    description: Tool repository
    default: "velis74/incremental-coverage-check"
  rep_ref:
    description: Repository branch
    default: "main"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ inputs.rep_ref }}
        repository: ${{ inputs.repository }}
        path: icc
    - run: pip3 install -r icc/requirements.txt
      shell: bash
    - run: git fetch origin ${{ github.base_ref }}:${{ github.base_ref }}
      shell: bash
    - name: Run coverage check
      run: python3 icc/main.py -w ${{ github.workspace }} -c ${{ inputs.head_ref }}  -b ${{ inputs.base_ref }} --clover-coverage-json ${{ inputs.clover_coverage_json }} --py-coverage-json ${{ inputs.py_coverage_json }} -l ${{ inputs.logging_level }} --gh-token ${{ github.token }}
      shell: bash

